### PR TITLE
required header with gcc 7.2.0 on archlinux

### PR DESCRIPTION
**Pull request by choener**
```uintptr_t``` undeclared.

### CODE REVIEW

**Comment by psibi** [comment]
@choener Can you see why the test is specifically failing for a single version of the compiler ?

**Comment by choener** [comment]
It looks like (```openAsFeed```) the specs are failing on opening www.google.com. You could try restarting travis-ci, this might be transient.

I don't think it actually has to do with my change, since the change just makes an import explicit.

**Comment by psibi** [comment]
I did restart and it resulted in the same error. Anyway, the PR shouldn't cause that problem. Thanks for the patch!

**Comment by beojan** [comment]
Can you make a new release with this patch, so it's installable as a stack dependency?

**Comment by psibi** [comment]
@beojan  A new version has been released.

**Pull request merged**
